### ISSUE TITLE
Update README with more info about the repo

### ISSUE THREAD

**Issue by BOLT04** [EddieJaoudeCommunity/LiveStream-GitOps-Demo#1]
Is there an ongoing project about GitOps on this repo? Maybe we could share at least a link to the livestream on the README, or elaborate on the contributions we want to have. For example being like a source of information about GitOps perhaps?

Let me know your thoughts 😃

**Comment by swade1987** [comment]
@BOLT04 the plan is for @eddiejaoude and I to do a live stream in a few weeks.

**Comment by eddiejaoude** [comment]
Thanks for raising the issue @BOLT04 . @swade1987 and me are still planning a few things out at the moment,.

Anything in particular you would like to see @BOLT04 ?

**Comment by BOLT04** [comment]
thanks for the response @eddiejaoude and @swade1987 😃. It would be cool to see something practical, maybe a demo example on GitHub (or anywhere that you guys feel its applicable) or even pick an existing repository and change it according to some GitOps practices, like maybe add a release pipeline (still not sure what GitOps is all about, so I'm shooting blindly 😅)

**Comment by eddiejaoude** [comment]
Great suggestions @BOLT04 👍 - I think there will be a demo too. I want to do something similar for EddieBot once I learn more from this session 🤓

**Comment by swade1987** [comment]
I was thinking we could take a very basic NodeJS application, dockerise it, push it to a registry and deploy it to kubernetes using GitOps practices.

**Comment by eddiejaoude** [comment]
node FTW 💪  ... lets do it 👍

**Comment by swade1987** [comment]
I already have one we can use I can port it over to this repo!

**Comment by eddiejaoude** [comment]
ok great 👍

**Comment by BOLT04** [comment]
Hi @swade1987 and @eddiejaoude, I'll be closing this issue since the live stream happened and the README was updated with tons of cool info to learn more about GitOps 👍 😃 

Thank you!

**Comment by eddiejaoude** [comment]
Thanks @BOLT04 👍
